#!/bin/sh

status=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`

if [ ${status} = "performance" ]; then
    sudo cpupower -c all frequency-set -g powersave
    echo "powersave"
else
    sudo cpupower -c all frequency-set -g performance
    echo "performance"
fi
