#!/bin/sh

if [ $# -lt 1 ];
then
    echo "Invalid number of arguments"
    echo "./procmemory <process name> [maxRAM]"
    exit 0
fi
process=$1
limit=$2
min=`cat /proc/meminfo | grep MemTotal | awk '{printf("%d\n",$2 / 1024)}'`
max=-1
sumavg=0
count=0
if [ $# -eq 1 ]; then
    limit=$min
fi


while true;
do
	NAME=`pgrep $process`
	if [ ${#NAME} -gt 0 ]; then
	    SIZE=$(pmap -x $NAME|grep total|awk '{sum+=$4} END{print sum;}')
	    VSIZE=$(pmap $NAME|grep total|grep -o "[0-9]*"|awk '{sum+=$process} END{print sum;}')
	    VSIZEMB=$((VSIZE/1024))
	    SIZEMB=$((SIZE/1024))
	    echo "Process= $process Size = $SIZEMB MB, VSize = $VSIZEMB MB"
	    if [ $max -lt $SIZEMB ]; then
	    	max=$SIZEMB
	    fi
	    if [ $min -gt $SIZEMB ]; then
	    	min=$SIZEMB
	    fi
	    sumavg=`expr $sumavg + $SIZEMB`
	    count=`expr $count + 1`
	    if [ $SIZEMB -gt $limit ]; then
	        printf "$process memory has exceeded.\n"
	    fi
		avg=`expr $sumavg / $count`
		trap "echo Min: $min MB, Max: $max MB, Avg: $avg MB; exit 0" 2
	fi
    sleep 1
done
