#!/bin/sh

if [ $# -ne 2 ];
then
    echo "Invalid number of arguments"
    echo "./procmemory <process name> <max RAM>"
    exit 0
fi

min=`cat /proc/meminfo | grep MemTotal | awk '{printf("%d\n",$2 / 1024)}'`
max=-1
sumavg=0
count=0

while true;
do
	NAME=`pgrep $1`
	if [ ${#NAME} -gt 0 ]; then
	    SIZE=$(pmap -x $NAME|grep total|awk '{sum+=$4} END{print sum;}')
	    VSIZE=$(pmap $NAME|grep total|grep -o "[0-9]*"|awk '{sum+=$1} END{print sum;}')
	    VSIZEMB=$((VSIZE/1024))
	    SIZEMB=$((SIZE/1024))
	    echo "Process= $1 Size = $SIZEMB MB, VSize = $VSIZEMB MB"
	    if [ $max -lt $SIZEMB ]; then
	    	max=$SIZEMB
	    fi
	    if [ $min -gt $SIZEMB ]; then
	    	min=$SIZEMB
	    fi
	    sumavg=`expr $sumavg + $SIZEMB`
	    count=`expr $count + 1`
	    if [ $SIZEMB -gt $2 ]; then
	        printf "$1 has exceeded.\n"
	    fi
		avg=`expr $sumavg / $count`
		trap "echo Min: $min MB, Max: $max MB, Avg: $avg MB; exit 0" 2
	fi
    sleep 1
done
