#!/bin/sh
if [ $# -eq 0 ];then
	echo "No arguments!"
	exit 0;
fi;

if echo $1 | egrep -q '[1-3]$'; then
	sudo sh -c 'echo '$1' >/proc/sys/vm/drop_caches'
	echo 'echo '$1' >/proc/sys/vm/drop_caches'
fi;
