#!/bin/sh
me=`basename $0`;

if [ $# -eq 0 ]; then
	echo "Usage: $me [ -s | -k | -o <color>]";
	echo "s is for start, k is for kill";
	echo "color is between 1000 and 10000";
	exit 1;
fi;

if [ $1 -gt 0 ]; then
	redshift -l 45.3:7.0 -t $1:$1 -o
	exit 0;
fi;

if [ "$1" = "-s" ]; then
	redshift -l 45.3:7.40 &
	exit 0;
fi;

if [ "$1" = "-k" ]; then
	pk=`ps -A | awk '/redshift/ {print $1;}'`
	kill $pk
	exit 0;
fi;
